services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.121.3
    container_name: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.lumiva.agency
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=https://n8n.lumiva.agency/
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
