import type { IntegrationHubCatalogEntry } from './integration-hub.types';

/**
 * Единый каталог сторонних коннекторов: где живёт в CRM и что умеет.
 * Секреты и tenant-данные сюда не входят.
 */
export const INTEGRATION_HUB_CATALOG: IntegrationHubCatalogEntry[] = [
  {
    id: 'woocommerce',
    lifecycle: 'live',
    modules: ['sales'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: true,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'slack',
    lifecycle: 'in_development',
    modules: ['automations'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'ms_teams',
    lifecycle: 'live',
    modules: ['automations'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'google_calendar',
    lifecycle: 'beta',
    modules: ['automations', 'calendar'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: true,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: true,
      leadCapture: false,
    },
  },
  {
    id: 'outlook',
    lifecycle: 'beta',
    modules: ['automations', 'calendar'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: true,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: true,
      leadCapture: false,
    },
  },
  {
    id: 'whatsapp',
    lifecycle: 'beta',
    modules: ['automations', 'leads'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: true,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: true,
    },
  },
  {
    id: 'mailchimp',
    lifecycle: 'beta',
    modules: ['automations', 'marketing'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'bitrix',
    lifecycle: 'beta',
    modules: ['automations', 'leads', 'projects'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'amocrm',
    lifecycle: 'beta',
    modules: ['automations', 'leads'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: true,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: true,
    },
  },
  {
    id: 'hubspot',
    lifecycle: 'beta',
    modules: ['automations', 'leads'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'zapier',
    lifecycle: 'in_development',
    modules: ['automations', 'leads', 'sales', 'workspace'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'google_ads',
    lifecycle: 'beta',
    modules: ['automations', 'marketing'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: true,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'google_analytics',
    lifecycle: 'beta',
    modules: ['automations', 'marketing'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: true,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'meta_ads',
    lifecycle: 'beta',
    modules: ['automations', 'marketing'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: true,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: '1c',
    lifecycle: 'in_development',
    modules: ['automations', 'sales', 'projects'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'sap',
    lifecycle: 'in_development',
    modules: ['automations', 'sales', 'projects'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'jira',
    lifecycle: 'in_development',
    modules: ['automations', 'projects'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'openai',
    lifecycle: 'in_development',
    modules: ['automations'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'wordpress_cf7',
    lifecycle: 'live',
    modules: ['leads', 'automations'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: true,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: true,
    },
  },
  {
    id: 'google_sheets',
    lifecycle: 'live',
    modules: ['workspace', 'leads', 'automations'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: false,
      oauthPlatformSupported: true,
      salesImport: false,
      workspaceTableSync: true,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'lumiva_client_cabinet',
    lifecycle: 'live',
    modules: ['leads', 'automations'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'lumiva_online_chat',
    lifecycle: 'live',
    modules: ['leads', 'automations'],
    capabilities: {
      outboundAutomationActions: false,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: false,
    },
  },
  {
    id: 'email',
    lifecycle: 'live',
    modules: ['workspace', 'leads', 'automations', 'email'],
    capabilities: {
      outboundAutomationActions: true,
      inboundWebhook: false,
      oauthPlatformSupported: false,
      salesImport: false,
      workspaceTableSync: false,
      calendarSync: false,
      leadCapture: true,
    },
  },
];
