export const TRIPLETS = [
  ['Продажи', 'Sales', 'Satışlar'],
  ['Проект создан', 'Project created', 'Proje oluşturuldu'],
  ['Проекты', 'Projects', 'Projeler'],
  [
    'Произвольный запрос к Google Ads API: метод, путь и JSON-тело (GAQL и т.д.). Для интеграций и нестандартных сценариев. Обычному пользователю для «отчёта из CRM» этот шаг не нужен — см. блок ниже.',
    'Arbitrary Google Ads API request: method, path, and JSON body (GAQL, etc.). For integrations and non-standard flows. Typical “CRM report” users do not need this step — see the block below.',
    'Serbest Google Ads API isteği: metot, yol ve JSON gövdesi (GAQL vb.). Entegrasyonlar ve özel senaryolar için. Tipik «CRM raporu» kullanıcıları bu adıma ihtiyaç duymaz — aşağıdaki bloğa bakın.',
  ],
  [
    'Произвольный запрос к Meta Marketing API (Graph): путь, метод, при необходимости тело. Для интеграций. Для типового отчёта из CRM по расписанию используйте «Отправить отчёт» — см. блок ниже.',
    'Arbitrary Meta Marketing API (Graph) request: path, method, body if needed. For integrations. For a typical scheduled CRM report use “Send report” — see the block below.',
    'Serbest Meta Marketing API (Graph) isteği: yol, metot, gerekirse gövde. Entegrasyonlar için. Zamanlanmış tipik CRM raporu için «Rapor gönder» kullanın — aşağıya bakın.',
  ],
  [
    'Пусто — весь ответ предыдущего шага. Пример: lastActionResult.data',
    'Empty — full response from the previous step. Example: lastActionResult.data',
    'Boş — önceki adımın tam yanıtı. Örnek: lastActionResult.data',
  ],
  [
    'Пусто — из лида или контакта в триггере ({{lead.email}}). Можно шаблон: {{lead.email}}',
    'Empty — from the lead or contact in the trigger ({{lead.email}}). You can use a template: {{lead.email}}',
    'Boş — tetikleyicideki lead veya kişiden ({{lead.email}}). Şablon: {{lead.email}}',
  ],
  [
    'Пусто — из подключения или api.hubapi.com. Пример: https://api-eu1.hubapi.com',
    'Empty — from the connection or api.hubapi.com. Example: https://api-eu1.hubapi.com',
    'Boş — bağlantıdan veya api.hubapi.com. Örnek: https://api-eu1.hubapi.com',
  ],
  ['Пусто — из подключения или primary.', 'Empty — from the connection or primary.', 'Boş — bağlantıdan veya primary.'],
  [
    'Пусто — календарь по умолчанию или значение из подключения.',
    'Empty — default calendar or value from the connection.',
    'Boş — varsayılan takvim veya bağlantıdaki değer.',
  ],
  ['Путь к данным (опционально)', 'Data path (optional)', 'Veri yolu (isteğe bağlı)'],
  ['Путь API', 'API path', 'API yolu'],
  ['Путь Graph (относительно /v…/)', 'Graph path (relative to /v…/)', 'Graph yolu (/v…/ göreli)'],
  ['Пятница', 'Friday', 'Cuma'],
  ['Развернуть', 'Expand', 'Genişlet'],
  ['Редактировать автоматизацию', 'Edit automation', 'Otomasyonu düzenle'],
  ['Режим валют', 'Currency mode', 'Para birimi modu'],
  ['Свернуть', 'Collapse', 'Daralt'],
  ['Свой JSON-тело (опционально)', 'Custom JSON body (optional)', 'Özel JSON gövdesi (isteğe bağlı)'],
  ['Сдвиг начала от момента срабатывания, мин', 'Start offset from trigger time, min', 'Tetik anından başlangıç kayması, dk'],
  ['Событие в Google Calendar', 'Google Calendar event', 'Google Calendar etkinliği'],
  ['Событие в Outlook (Microsoft 365)', 'Outlook event (Microsoft 365)', 'Outlook etkinliği (Microsoft 365)'],
  ['Содержание заметки', 'Note content', 'Not içeriği'],
  [
    'Создаёт в Mailchimp обычную (regular) кампанию на всю выбранную аудиторию, подставляет HTML и сразу отправляет. Подходит для рассылки при событии в CRM (например новый продукт в таблице или по расписанию). Один шаг = одна отправка за запуск сценария.',
    'Creates a regular Mailchimp campaign for the whole selected audience, injects HTML, and sends immediately. Good for broadcasts on a CRM event (e.g. new product row) or on a schedule. One step = one send per scenario run.',
    'Seçilen tüm kitle için Mailchimp’te regular kampanya oluşturur, HTML yerleştirir ve hemen gönderir. CRM olayında (ör. tabloda yeni ürün) veya zamanlamada uygun. Bir adım = senaryo çalışması başına bir gönderim.',
  ],
  [
    'Создаёт событие в календаре через Google Calendar API. В подключении — OAuth access token с scope календаря; при необходимости укажите ID календаря (по умолчанию primary).',
    'Creates a calendar event via Google Calendar API. The connection holds an OAuth access token with calendar scope; set calendar ID if needed (default primary).',
    'Google Calendar API ile takvim etkinliği oluşturur. Bağlantıda takvim kapsamı OAuth erişim jetonu; gerekirse takvim ID (varsayılan primary).',
  ],
  [
    'Создаёт событие через Microsoft Graph (календарь пользователя). Время начала и конца передаётся в UTC. Нужен токен с правами на календарь.',
    'Creates an event via Microsoft Graph (user calendar). Start and end are sent in UTC. Token must have calendar permissions.',
    'Microsoft Graph ile (kullanıcı takvimi) etkinlik oluşturur. Başlangıç/bitiş UTC’de gönderilir. Takvim izinli jeton gerekir.',
  ],
  ['Создать', 'Create', 'Oluştur'],
  ['Создать автоматизацию', 'Create automation', 'Otomasyon oluştur'],
  ['Создать задачу компании', 'Create company task', 'Şirket görevi oluştur'],
  ['Создать заметку', 'Create note', 'Not oluştur'],
  ['Сохранение...', 'Saving…', 'Kaydediliyor…'],
  ['Сохранить', 'Save', 'Kaydet'],
  ['Среда', 'Wednesday', 'Çarşamba'],
  ['Срок (дата)', 'Due date', 'Bitiş (tarih)'],
  ['Статус', 'Status', 'Durum'],
  ['Статус задачи изменен', 'Task status changed', 'Görev durumu değişti'],
  ['Статус записи изменён (custom object)', 'Record status changed (custom object)', 'Kayıt durumu değişti (özel nesne)'],
  ['Статус лида изменен', 'Lead status changed', 'Lead durumu değişti'],
  ['Статус подписки', 'Subscription status', 'Abonelik durumu'],
  ['Статус продажи изменен', 'Sale status changed', 'Satış durumu değişti'],
  ['Статус проекта изменен', 'Project status changed', 'Proje durumu değişti'],
  ['Суббота', 'Saturday', 'Cumartesi'],
  ['Сфера', 'Scope', 'Kapsam'],
  [
    'Та же аудитория, что в Mailchimp. В аудитории должны быть подписчики; домен reply-to — верифицирован в Mailchimp.',
    'Same audience as in Mailchimp. The audience must have subscribers; reply-to domain is verified in Mailchimp.',
    'Mailchimp’tekiyle aynı kitle. Kitlede aboneler olmalı; yanıtla (reply-to) alanı Mailchimp’te doğrulanmış olmalı.',
  ],
  ['Тег *', 'Tag *', 'Etiket *'],
  ['Текст', 'Text', 'Metin'],
  ['Текст (если не задан свой JSON ниже)', 'Text (if custom JSON below is not set)', 'Metin (aşağıda özel JSON yoksa)'],
  ['Текст (поддерживается Markdown в Teams)', 'Text (Markdown supported in Teams)', 'Metin (Teams’te Markdown desteklenir)'],
  [
    'Текст письма. Переменные: {{lead.name}}, {{lead.email}}, {{lead.phone}}, {{lead.status}}, {{contact.email}}, {{contact.fullName}}',
    'Email body. Variables: {{lead.name}}, {{lead.email}}, {{lead.phone}}, {{lead.status}}, {{contact.email}}, {{contact.fullName}}',
    'E-posta gövdesi. Değişkenler: {{lead.name}}, {{lead.email}}, {{lead.phone}}, {{lead.status}}, {{contact.email}}, {{contact.fullName}}',
  ],
  ['Текст события (опционально)', 'Event text (optional)', 'Etkinlik metni (isteğe bağlı)'],
  ['Текст сообщения', 'Message text', 'Mesaj metni'],
  ['Текстовая версия (рекомендуется)', 'Plain text version (recommended)', 'Düz metin sürümü (önerilir)'],
  ['Тело запроса (JSON-объект)', 'Request body (JSON object)', 'İstek gövdesi (JSON nesnesi)'],
  ['Тело запроса (JSON)', 'Request body (JSON)', 'İstek gövdesi (JSON)'],
  ['Тема', 'Subject', 'Konu'],
  [
    'Тема и текст будут взяты из шаблона с подстановкой переменных из триггера',
    'Subject and body will be taken from the template with variables from the trigger',
    'Konu ve gövde, tetikleyiciden değişkenlerle şablondan alınır',
  ],
  ['Тема письма', 'Email subject', 'E-posta konusu'],
  ['Тема письма *', 'Email subject *', 'E-posta konusu *'],
];
