export const TRIPLETS = [
  ['Тема события', 'Event subject', 'Etkinlik konusu'],
  ['Тип действия', 'Action type', 'Eylem türü'],
  ['Тип отчёта', 'Report type', 'Rapor türü'],
  ['Токен доступа (override)', 'Access token (override)', 'Erişim jetonu (üzerine yaz)'],
  ['Только выбранная', 'Selected only', 'Yalnızca seçilen'],
  ['Триггер (событие) *', 'Trigger (event) *', 'Tetikleyici (olay) *'],
  ['Удалить', 'Delete', 'Sil'],
  ['Условия', 'Conditions', 'Koşullar'],
  ['Форматы вложений', 'Attachment formats', 'Ek biçimleri'],
  ['Хост API (override)', 'API host (override)', 'API ana makinesi (üzerine yaz)'],
  ['Часовой пояс', 'Time zone', 'Saat dilimi'],
  ['Часовой пояс (IANA)', 'Time zone (IANA)', 'Saat dilimi (IANA)'],
  ['Частота', 'Frequency', 'Sıklık'],
  ['Четверг', 'Thursday', 'Perşembe'],
  ['Что выполнить при срабатывании триггера', 'What to run when the trigger fires', 'Tetikleyici çalışınca ne yapılsın'],
  ['Шаблон письма', 'Email template', 'E-posta şablonu'],
  ['Шаг', 'Step', 'Adım'],
  [
    'Это не мастер отчёта: здесь настраивается прямой вызов рекламного API. Чтобы получать готовый отчёт по CRM (продажи, лиды, задачи…) на почту или в Telegram без путей и JSON — используйте действие «Отправить отчёт».',
    'This is not a report wizard: here you configure a direct ads API call. For a ready-made CRM report (sales, leads, tasks…) to email or Telegram without paths and JSON — use “Send report”.',
    'Bu bir rapor sihirbazı değil: burada doğrudan reklam API çağrısı ayarlanır. CRM’den hazır raporu (satışlar, leadler, görevler…) yol/JSON olmadan e-posta veya Telegram’a almak için «Rapor gönder» kullanın.',
  ],
  [
    'Этот шаг — для прямых вызовов Graph API. Готовый отчёт из CRM на почту или в Telegram настраивается действием «Отправить отчёт» (тип отчёта, канал, расписание).',
    'This step is for direct Graph API calls. A ready CRM report to email or Telegram is configured with “Send report” (report type, channel, schedule).',
    'Bu adım doğrudan Graph API çağrıları içindir. CRM’den hazır rapor e-posta/Telegram için «Rapor gönder» ile ayarlanır (rapor türü, kanal, zamanlama).',
  ],
  ['Access token (override)', 'Access token (override)', 'Access token (üzerine yaz)'],
  ['Audience ID (List ID)', 'Audience ID (List ID)', 'Audience ID (Liste ID)'],
  ['Bot ID', 'Bot ID', 'Bot ID'],
  [
    'CRM при выполнении шага обменяет refresh token на access token (как при синхронизации отчётов). Поля override ниже имеют приоритет, если заполнены.',
    'The CRM exchanges refresh token for access token when the step runs (as for report sync). Override fields below take priority if filled.',
    'Adım çalışırken CRM refresh jetonunu access jetonuyla değiştirir (rapor senkronu gibi). Doldurulursa aşağıdaki override alanları önceliklidir.',
  ],
  ['crm.lead.add', 'crm.lead.add', 'crm.lead.add'],
  ['Customer ID (override, только цифры)', 'Customer ID (override, digits only)', 'Customer ID (üzerine yaz, yalnızca rakam)'],
  ['Developer token (override)', 'Developer token (override)', 'Developer token (üzerine yaz)'],
  ['Email', 'Email', 'E-posta'],
  ['Email (опционально)', 'Email (optional)', 'E-posta (isteğe bağlı)'],
  ['Email аккаунт *', 'Email account *', 'E-posta hesabı *'],
  ['Email отправлен', 'Email sent', 'E-posta gönderildi'],
  ['Email получателей', 'Email recipients', 'E-posta alıcıları'],
  ['Email получен', 'Email received', 'E-posta alındı'],
  [
    'email@example.com или оставьте пустым для использования email из лида',
    'email@example.com or leave empty to use the lead’s email',
    'email@example.com veya lead e-postasını kullanmak için boş bırakın',
  ],
  ['Excel (XLSX)', 'Excel (XLSX)', 'Excel (XLSX)'],
  ['HTML письма *', 'Email HTML *', 'E-posta HTML *'],
  ['HTTP-метод', 'HTTP method', 'HTTP metodu'],
  ['ID календаря (override)', 'Calendar ID (override)', 'Takvim ID (üzerine yaz)'],
  ['ID календаря Graph (override)', 'Graph calendar ID (override)', 'Graph takvim ID (üzerine yaz)'],
  ['ID компании (если не из лида)', 'Company ID (if not from lead)', 'Şirket ID (lead’den değilse)'],
  ['IF: Когда', 'IF: When', 'IF: Ne zaman'],
  ['JSON', 'JSON', 'JSON'],
  ['Mailchimp / аудитория', 'Mailchimp / audience', 'Mailchimp / kitle'],
  ['Mailchimp / рассылка аудитории', 'Mailchimp / audience broadcast', 'Mailchimp / kitle yayını'],
  ['me/adaccounts?fields=id,name', 'me/adaccounts?fields=id,name', 'me/adaccounts?fields=id,name'],
  ['Merge fields (JSON, опционально)', 'Merge fields (JSON, optional)', 'Birleştirme alanları (JSON, isteğe bağlı)'],
  ['OAuth access token (override)', 'OAuth access token (override)', 'OAuth access token (üzerine yaz)'],
  ['Override access token (без подключения)', 'Override access token (no connection)', 'Access token override (bağlantı olmadan)'],
  ['PDF (текст JSON)', 'PDF (JSON text)', 'PDF (JSON metni)'],
  ['Phone number ID (если не из подключения)', 'Phone number ID (if not from connection)', 'Phone number ID (bağlantıdan değilse)'],
  [
    'Plain text для клиентов без HTML; уменьшает попадание в спам.',
    'Plain text for clients without HTML; reduces spam likelihood.',
    'HTML olmayan istemciler için düz metin; spam riskini azaltır.',
  ],
  ['Reply-To (email) *', 'Reply-To (email) *', 'Reply-To (e-posta) *'],
  ['Telegram', 'Telegram', 'Telegram'],
  ['Telegram сообщение получено', 'Telegram message received', 'Telegram mesajı alındı'],
  ['Telegram User ID', 'Telegram User ID', 'Telegram kullanıcı ID'],
  ['THEN: Сделать', 'THEN: Do', 'THEN: Yap'],
  ['URL *', 'URL *', 'URL *'],
  ['UUID бота (Telegram CRM)', 'Bot UUID (Telegram CRM)', 'Bot UUID (Telegram CRM)'],
  [
    'WhatsApp Cloud API: сообщение типа text. В подключении должны быть Phone number ID и токен из Meta.',
    'WhatsApp Cloud API: text message type. The connection must include Phone number ID and token from Meta.',
    'WhatsApp Cloud API: text mesaj türü. Bağlantıda Meta’dan Phone number ID ve jeton olmalıdır.',
  ],
];
