/** [Russian, English, Turkish] — same order as form-unique-ru-strings.json (sorted) */
export const TRIPLETS = [
  ['— выберите подключение —', '— select a connection —', '— bağlantı seçin —'],
  ['— не использовать маркетинг —', '— do not use marketing connection —', '— pazarlama bağlantısı kullanma —'],
  [
    '«Pending» имеет смысл, если в Mailchimp для аудитории включён double opt-in; иначе чаще используйте «Подписан».',
    '“Pending” makes sense if double opt-in is enabled for the audience in Mailchimp; otherwise prefer “Subscribed”.',
    'Mailchimp’te kitle için çift onay (double opt-in) açıksa “Pending” anlamlıdır; aksi halde “Abone” kullanın.',
  ],
  ['/api/v4/leads', '/api/v4/leads', '/api/v4/leads'],
  ['/crm/v3/objects/contacts', '/crm/v3/objects/contacts', '/crm/v3/objects/contacts'],
  [
    '/customers/{{customerId}}/googleAds:searchStream',
    '/customers/{{customerId}}/googleAds:searchStream',
    '/customers/{{customerId}}/googleAds:searchStream',
  ],
  [
    'Автоматизация будет выполняться только если включена',
    'The automation runs only when it is enabled.',
    'Otomasyon yalnızca açıkken çalışır.',
  ],
  ['Автоматизация сохранена', 'Automation saved.', 'Otomasyon kaydedildi.'],
  ['Активна', 'Active', 'Aktif'],
  ['Базовый URL аккаунта (override)', 'Account base URL (override)', 'Hesap temel URL’si (üzerine yaz)'],
  ['Без доп. параметров', 'No extra parameters', 'Ek parametre yok'],
  [
    'Берёт результат предыдущего шага (например ответ Google Ads / Meta из маркетинга), формирует файлы и отправляет.',
    'Takes the previous step result (e.g. Google Ads / Meta response from marketing), builds files, and sends them.',
    'Önceki adımın sonucunu alır (ör. pazarlamadan Google Ads / Meta yanıtı), dosyalar oluşturur ve gönderir.',
  ],
  [
    'Берётся access token из настроек маркетинговой интеграции. Поле override ниже имеет приоритет.',
    'Access token is taken from the marketing integration settings. The override field below takes priority.',
    'Erişim jetonu pazarlama entegrasyonu ayarlarından alınır. Aşağıdaki override alanı önceliklidir.',
  ],
  ['Быстрый старт по сущностям', 'Quick start by entity', 'Varlığa göre hızlı başlangıç'],
  [
    'В Mailchimp: Audience → Settings → Audience name and defaults — поле Audience ID.',
    'In Mailchimp: Audience → Settings → Audience name and defaults — the Audience ID field.',
    'Mailchimp: Audience → Settings → Audience name and defaults — Audience ID alanı.',
  ],
  [
    'В Telegram каждый файл уходит отдельным сообщением; чат с ботом должен уже существовать (как для шага «Отправить отчёт»).',
    'In Telegram each file is sent as a separate message; the chat with the bot must already exist (as for “Send report”).',
    'Telegram’da her dosya ayrı mesajdır; bot sohbeti zaten olmalıdır (“Rapor gönder” gibi).',
  ],
  ['Валюта отображения', 'Display currency', 'Görüntüleme para birimi'],
  [
    'Видно только в Mailchimp; по умолчанию = тема. Макс. 100 символов.',
    'Visible only in Mailchimp; defaults to subject. Max 100 characters.',
    'Yalnızca Mailchimp’te görünür; varsayılan konu. En fazla 100 karakter.',
  ],
  ['Внутреннее название кампании', 'Internal campaign name', 'Kampanya iç adı'],
  ['Воскресенье', 'Sunday', 'Pazar'],
  ['Временный override токена', 'Temporary token override', 'Geçici jeton üzerine yazma'],
  ['Время', 'Time', 'Saat'],
  ['Вторник', 'Tuesday', 'Salı'],
  [
    'Выберите шаблон для использования темы и текста из шаблона, или оставьте пустым для ручного ввода',
    'Pick a template to use subject and body from it, or leave empty for manual entry.',
    'Konu ve gövde için şablon seçin veya manuel giriş için boş bırakın.',
  ],
  ['Выберите email аккаунт', 'Select an email account', 'E-posta hesabı seçin'],
  [
    'Выбрана интеграция из маркетинга — access token берётся оттуда. Дублировать ввод не нужно; поле override ниже только при необходимости.',
    'A marketing integration is selected — the access token comes from there. No need to duplicate; use override below only if needed.',
    'Pazarlama entegrasyonu seçildi — erişim jetonu oradan gelir. Tekrar girmeyin; gerekirse aşağıdaki override.',
  ],
  [
    'Выбрана интеграция из маркетинга — developer token, OAuth и Customer ID подтягиваются оттуда при запуске шага. Вводить то же самое здесь не нужно; поля ниже только если нужен override.',
    'A marketing integration is selected — developer token, OAuth, and Customer ID are pulled when the step runs. You do not need to re-enter them here; fields below are overrides only.',
    'Pazarlama entegrasyonu seçildi — developer token, OAuth ve Customer ID adımda çekilir. Burada tekrarlamayın; alanlar yalnızca override içindir.',
  ],
  ['Вызвать Webhook', 'Call webhook', "Webhook'u çağır"],
  ['Вызов Битрикс24 (REST)', 'Bitrix24 call (REST)', 'Bitrix24 çağrısı (REST)'],
  [
    'Вызов метода REST Битрикс24 через входящий вебхук. Права определяются правами вебхука в портале.',
    'Calls a Bitrix24 REST method via an inbound webhook. Permissions follow the webhook rights on the portal.',
    'Gelen webhook üzerinden Bitrix24 REST metodu çağrılır. Yetkiler portaldaki webhook ile sınırlıdır.',
  ],
  [
    'Данные из таблицы маркетингового трафика CRM: синхронизации Google Ads, Meta, Яндекс.Метрики, GA4 и импорты. Если интеграции не настроены или не запускались — в отчёте будет мало или нет строк.',
    'Data from the CRM marketing traffic table: Google Ads, Meta, Yandex.Metrica, GA4 syncs and imports. If integrations are not set up or never ran, the report may have few or no rows.',
    'CRM pazarlama trafiği tablosundan veri: Google Ads, Meta, Yandex.Metrica, GA4 senkronları ve içe aktarmalar. Entegrasyonlar yoksa veya çalışmadıysa raporda az veya satır olmayabilir.',
  ],
  ['Дата', 'Date', 'Tarih'],
  ['Дата по', 'To date', 'Bitiş tarihi'],
  ['Дата продажи', 'Sale date', 'Satış tarihi'],
  ['Дата с', 'From date', 'Başlangıç tarihi'],
  ['Дата создания', 'Created date', 'Oluşturulma tarihi'],
  ['Действие', 'Action', 'Eylem'],
  ['Действий пока нет', 'No actions yet', 'Henüz eylem yok'],
  ['Действия (THEN)', 'Actions (THEN)', 'Eylemler (THEN)'],
  ['Действия по расписанию', 'Scheduled actions', 'Zamanlanmış eylemler'],
  ['День месяца', 'Day of month', 'Ayın günü'],
  ['День недели', 'Day of week', 'Haftanın günü'],
  ['Длительность, мин', 'Duration, min', 'Süre, dk'],
  [
    'Для лидов с компанией UUID компании подставится автоматически.',
    'For leads with a company, the company UUID is filled automatically.',
    'Şirketi olan leadlerde şirket UUID’si otomatik doldurulur.',
  ],
  [
    'Для создания контакта — объект properties. Плейсхолдеры {{lead.email}}. Для GET тело не используется.',
    'For contact creation — a properties object. Placeholders {{lead.email}}. GET does not use a body.',
    'Kişi oluşturma için properties nesnesi. Yer tutucular {{lead.email}}. GET için gövde kullanılmaz.',
  ],
  [
    'Для crm.lead.add обычно {"fields":{"TITLE":"…","NAME":"…"}}. Пусто — {}. Поддерживаются плейсхолдеры {{lead.name}} и т.д.',
    'For crm.lead.add usually {"fields":{"TITLE":"…","NAME":"…"}}. Empty — {}. Placeholders like {{lead.name}} are supported.',
    'crm.lead.add için genelde {"fields":{"TITLE":"…","NAME":"…"}}. Boş — {}. {{lead.name}} gibi yer tutucular desteklenir.',
  ],
  [
    'Для POST /api/v4/leads обычно массив сделок. Плейсхолдеры: {{lead.name}}. Для GET оставьте пустым.',
    'For POST /api/v4/leads usually an array of deals. Placeholders: {{lead.name}}. For GET leave empty.',
    'POST /api/v4/leads için genelde fırsat dizisi. Yer tutucular: {{lead.name}}. GET için boş bırakın.',
  ],
  [
    'Для POST/PATCH/PUT — тело Google Ads API. Плейсхолдеры {{lead.name}} и т.д. Для GET не отправляется.',
    'For POST/PATCH/PUT — Google Ads API body. Placeholders {{lead.name}}, etc. Not sent for GET.',
    'POST/PATCH/PUT için Google Ads API gövdesi. Yer tutucular {{lead.name}} vb. GET için gönderilmez.',
  ],
  [
    'Для POST/PATCH/PUT — JSON-тело. Для GET не используется. Плейсхолдеры {{lead.name}} и т.д.',
    'For POST/PATCH/PUT — JSON body. Not used for GET. Placeholders {{lead.name}}, etc.',
    'POST/PATCH/PUT için JSON gövdesi. GET için kullanılmaz. Yer tutucular {{lead.name}} vb.',
  ],
];
