export const TRIPLETS = [
  [
    'Ниже добавьте шаги: например «Запрос Google Ads API» (интеграция из маркетинга), затем «Отправить данные шага» — JSON/XLSX/PDF на почту или в Telegram. Расписание: частота и время в блоке выше.',
    'Add steps below: for example “Google Ads API request” (marketing integration), then “Send step data” — JSON/XLSX/PDF to email or Telegram. Schedule: frequency and time in the block above.',
    'Aşağıya adımlar ekleyin: örn. «Google Ads API isteği» (pazarlama entegrasyonu), ardından «Adım verisini gönder» — e-posta veya Telegram’a JSON/XLSX/PDF. Zamanlama: yukarıdaki blokta sıklık ve saat.',
  ],
  ['Новая продажа -> отчёт и заметка', 'New sale -> report and note', 'Yeni satış -> rapor ve not'],
  ['Новый лид -> письмо и заметка', 'New lead -> email and note', 'Yeni lead -> e-posta ve not'],
  ['Новый лид: {{lead.name}} · {{lead.email}}', 'New lead: {{lead.name}} · {{lead.email}}', 'Yeni lead: {{lead.name}} · {{lead.email}}'],
  ['Новый проект -> заметка и статус', 'New project -> note and status', 'Yeni proje -> not ve durum'],
  ['Новый статус *', 'New status *', 'Yeni durum *'],
  ['Номер получателя', 'Recipient number', 'Alıcı numarası'],
  ['Нужен просто отчёт раз в неделю?', 'Need just a weekly report?', 'Haftada bir rapor yeterli mi?'],
  ['Обновить поле', 'Update field', 'Alanı güncelle'],
  [
    'Объект полей Mailchimp, например {"FNAME":"{{lead.name}}"}. Ключи — как в вашей аудитории. Числа и логические значения из JSON сервер приведёт к строкам для API Mailchimp.',
    'Mailchimp merge fields object, e.g. {"FNAME":"{{lead.name}}"}. Keys must match your audience. Numbers and booleans from JSON are coerced to strings for the Mailchimp API.',
    'Mailchimp birleştirme alanları nesnesi, örn. {"FNAME":"{{lead.name}}"}. Anahtarlar kitlenize uygun olmalı. JSON’daki sayı ve boolean değerler Mailchimp API için metne dönüştürülür.',
  ],
  ['Ожидает подтверждения (pending, double opt-in)', 'Awaiting confirmation (pending, double opt-in)', 'Onay bekliyor (pending, çift onay)'],
  ['Описание', 'Description', 'Açıklama'],
  ['Описание (опционально)', 'Description (optional)', 'Açıklama (isteğe bağlı)'],
  ['Основная информация', 'Basic information', 'Temel bilgiler'],
  ['Ответственный (user id)', 'Owner (user id)', 'Sorumlu (user id)'],
  [
    'Отдельного подключения Google Ads в «Автоматизации → Интеграции» нет — для этого шага это не требуется, если сверху выбрана маркетинговая интеграция.',
    'There is no separate Google Ads connection under Automations → Integrations — not required for this step if a marketing integration is selected above.',
    'Otomasyonlar → Entegrasyonlar altında ayrı Google Ads bağlantısı yok — yukarıda pazarlama entegrasyonu seçildiyse bu adım için gerekmez.',
  ],
  [
    'Отдельного подключения Meta в «Автоматизации → Интеграции» нет — при выбранной маркетинговой интеграции это не обязательно.',
    'There is no separate Meta connection under Automations → Integrations — optional when a marketing integration is selected.',
    'Otomasyonlar → Entegrasyonlar altında ayrı Meta bağlantısı yok — pazarlama entegrasyonu seçiliyse zorunlu değil.',
  ],
  ['Открыть интеграции', 'Open integrations', 'Entegrasyonları aç'],
  ['Отмена', 'Cancel', 'İptal'],
  ['Отправить в Microsoft Teams', 'Send to Microsoft Teams', "Microsoft Teams'e gönder"],
  ['Отправить в Slack', 'Send to Slack', "Slack'e gönder"],
  ['Отправить в WhatsApp', 'Send to WhatsApp', "WhatsApp'a gönder"],
  ['Отправить в Zapier (Catch Hook)', 'Send to Zapier (Catch Hook)', "Zapier'a gönder (Catch Hook)"],
  ['Отправить данные шага (JSON / Excel / PDF)', 'Send step data (JSON / Excel / PDF)', 'Adım verisini gönder (JSON / Excel / PDF)'],
  ['Отправить отчёт', 'Send report', 'Rapor gönder'],
  ['Отправить Email', 'Send Email', 'E-posta gönder'],
  ['Отправить Telegram', 'Send Telegram', 'Telegram gönder'],
  [
    'Отправка в канал через Slack Incoming Webhook. Сначала добавьте подключение Slack (Автоматизации → Интеграции → Подключить), затем выберите его здесь или вставьте URL вручную.',
    'Post to a channel via Slack Incoming Webhook. First add a Slack connection (Automations → Integrations → Connect), then select it here or paste the URL manually.',
    'Slack Incoming Webhook ile kanala gönderim. Önce Slack bağlantısı ekleyin (Otomasyonlar → Entegrasyonlar → Bağla), sonra burada seçin veya URL’yi elle yapıştırın.',
  ],
  [
    'Отправка JSON в Zapier Catch Hook (или аналог Make через webhook).',
    'Send JSON to Zapier Catch Hook (or a Make equivalent via webhook).',
    'Zapier Catch Hook’a JSON gönderin (veya webhook ile Make benzeri).',
  ],
  ['Отчёт по расписанию', 'Scheduled report', 'Zamanlanmış rapor'],
  ['Отчёты', 'Reports', 'Raporlar'],
  ['Ошибка загрузки автоматизации', 'Failed to load automation', 'Otomasyon yüklenemedi'],
  ['Ошибка сохранения', 'Save failed', 'Kaydetme hatası'],
  ['Период данных в отчёте (опционально)', 'Report data period (optional)', 'Rapor veri dönemi (isteğe bağlı)'],
  ['Поддерживаются переменные, например {{lead.name}}.', 'Variables are supported, e.g. {{lead.name}}.', 'Değişkenler desteklenir, örn. {{lead.name}}.'],
  ['Подключение Битрикс24 из CRM', 'Bitrix24 connection from CRM', 'CRM’den Bitrix24 bağlantısı'],
  ['Подключение amoCRM из CRM', 'amoCRM connection from CRM', 'CRM’den amoCRM bağlantısı'],
  ['Подключение Google Ads из CRM (опционально)', 'Google Ads connection from CRM (optional)', 'CRM’den Google Ads bağlantısı (isteğe bağlı)'],
  ['Подключение Google Calendar из CRM', 'Google Calendar connection from CRM', 'CRM’den Google Calendar bağlantısı'],
  ['Подключение HubSpot из CRM', 'HubSpot connection from CRM', 'CRM’den HubSpot bağlantısı'],
  ['Подключение Mailchimp из CRM', 'Mailchimp connection from CRM', 'CRM’den Mailchimp bağlantısı'],
  ['Подключение Meta Ads из CRM (опционально)', 'Meta Ads connection from CRM (optional)', 'CRM’den Meta Ads bağlantısı (isteğe bağlı)'],
  ['Подключение Microsoft 365 / Outlook из CRM', 'Microsoft 365 / Outlook connection from CRM', 'CRM’den Microsoft 365 / Outlook bağlantısı'],
  ['Подключение Slack из CRM', 'Slack connection from CRM', "CRM'den Slack bağlantısı"],
  ['Подключение Teams из CRM', 'Teams connection from CRM', "CRM'den Teams bağlantısı"],
  ['Подключение WhatsApp из CRM', 'WhatsApp connection from CRM', "CRM'den WhatsApp bağlantısı"],
  ['Подключение Zapier из CRM', 'Zapier connection from CRM', "CRM'den Zapier bağlantısı"],
  ['Подписан (subscribed)', 'Subscribed', 'Abone (subscribed)'],
  [
    'Подставляется в путь как {{customerId}}. Если в подключении указан Customer ID в «Webhook URL» — он подхватится автоматически.',
    'Inserted into the path as {{customerId}}. If Customer ID is set in “Webhook URL” on the connection, it is picked up automatically.',
    'Yola {{customerId}} olarak eklenir. Bağlantıda «Webhook URL» içinde Customer ID varsa otomatik alınır.',
  ],
  [
    'Полное письмо для всей аудитории. Можно скопировать из «Письма» / маркетинговых шаблонов.',
    'Full email for the entire audience. You can copy from Emails / marketing templates.',
    'Tüm kitle için tam e-posta. «E-postalar» / pazarlama şablonlarından kopyalayabilirsiniz.',
  ],
  ['Получатели email (через запятую)', 'Email recipients (comma-separated)', 'E-posta alıcıları (virgülle)'],
  ['Получатель', 'Recipient', 'Alıcı'],
  ['Пользовательские таблицы', 'Custom tables', 'Özel tablolar'],
  ['Понедельник', 'Monday', 'Pazartesi'],
  ['Предпросмотр сценария', 'Scenario preview', 'Senaryo önizlemesi'],
  ['Приоритет (число)', 'Priority (number)', 'Öncelik (sayı)'],
  ['Продажа обновлена', 'Sale updated', 'Satış güncellendi'],
  ['Продажа создана', 'Sale created', 'Satış oluşturuldu'],
];
