export const TRIPLETS = [
  ['Добавить', 'Add', 'Ekle'],
  ['Добавить аккаунт', 'Add account', 'Hesap ekle'],
  ['Добавить действие', 'Add action', 'Eylem ekle'],
  ['Добавить тег', 'Add tag', 'Etiket ekle'],
  ['Добавить условие', 'Add condition', 'Koşul ekle'],
  [
    'Добавляет или обновляет подписчика в выбранной аудитории Mailchimp (Marketing API). Email берётся из триггера (лид/контакт) или из поля ниже.',
    'Adds or updates a subscriber in the selected Mailchimp audience (Marketing API). Email comes from the trigger (lead/contact) or from the field below.',
    'Seçilen Mailchimp kitlesinde aboneyi ekler veya günceller (Marketing API). E-posta tetikleyiciden (lead/kişi) veya aşağıdaki alandan gelir.',
  ],
  [
    'Должен быть адрес с домена, подтверждённого в Mailchimp (Website / Domains), иначе API вернёт ошибку.',
    'Must be an address on a domain verified in Mailchimp (Website / Domains), otherwise the API returns an error.',
    'Mailchimp’te doğrulanmış (Website / Domains) bir alan adındaki adres olmalıdır; aksi halde API hata döner.',
  ],
  [
    'Должен содержать /rest/ и заканчиваться слэшем (или будет добавлен автоматически на сервере).',
    'Must contain /rest/ and end with a slash (or it will be appended on the server).',
    '/rest/ içermeli ve slash ile bitmelidir (sunucuda otomatik eklenebilir).',
  ],
  ['Ежедневно', 'Daily', 'Günlük'],
  ['Ежеквартально', 'Quarterly', 'Üç aylık'],
  ['Ежемесячно', 'Monthly', 'Aylık'],
  ['Еженедельно', 'Weekly', 'Haftalık'],
  [
    'Если выбрано подключение с developer token — поле можно оставить пустым.',
    'If a connection with developer token is selected, you can leave the field empty.',
    'Developer token’lı bağlantı seçildiyse alanı boş bırakabilirsiniz.',
  ],
  [
    'Если не заполнено — период считается по «Частоте» (как окно от сегодня назад). Даты — календарные дни в UTC. Для ручного «Отправить сейчас» период задаётся в отдельном окне.',
    'If empty, the period is derived from “Frequency” (window back from today). Dates are calendar days in UTC. For manual “Run now”, the period is set in a separate dialog.',
    'Boşsa dönem «Sıklık»ten türetilir (bugünden geriye). Tarihler UTC takvim günüdür. Manuel «Şimdi çalıştır» için dönem ayrı pencerede.',
  ],
  [
    'Если поле JSON пустое, в Zapier уйдёт объект с полями source, text, triggerEvent, at.',
    'If the JSON field is empty, Zapier receives an object with source, text, triggerEvent, at.',
    'JSON alanı boşsa Zapier’a source, text, triggerEvent, at alanlı nesne gider.',
  ],
  [
    'Если пусто — берётся phone лида/контакта из триггера. Цифры с кодом страны.',
    'If empty, the lead/contact phone from the trigger is used. Digits with country code.',
    'Boşsa tetikleyicideki lead/kişi telefonu kullanılır. Ülke kodlu rakamlar.',
  ],
  [
    'Если указано, имеет приоритет над выбранным подключением. Должен быть https://hooks.slack.com/services/…',
    'If set, it overrides the selected connection. Must be https://hooks.slack.com/services/…',
    'Doldurulursa seçilen bağlantının üzerine yazar. https://hooks.slack.com/services/… olmalıdır.',
  ],
  ['Заголовки (JSON)', 'Headers (JSON)', 'Üst bilgiler (JSON)'],
  ['Заголовок задачи', 'Task title', 'Görev başlığı'],
  ['Заголовок карточки', 'Card title', 'Kart başlığı'],
  ['Загрузка аккаунтов...', 'Loading accounts…', 'Hesaplar yükleniyor…'],
  ['Загрузка шаблонов...', 'Loading templates…', 'Şablonlar yükleniyor…'],
  ['Задача обновлена', 'Task updated', 'Görev güncellendi'],
  ['Задача создана', 'Task created', 'Görev oluşturuldu'],
  ['Задачи', 'Tasks', 'Görevler'],
  ['Заменить этот шаг на «Отправить отчёт»', 'Replace this step with “Send report”', 'Bu adımı «Rapor gönder» ile değiştir'],
  ['Заметка создана', 'Note created', 'Not oluşturuldu'],
  ['Заметки', 'Notes', 'Notlar'],
  ['Запись обновлена (custom object)', 'Record updated (custom object)', 'Kayıt güncellendi (özel nesne)'],
  ['Запись создана (custom object)', 'Record created (custom object)', 'Kayıt oluşturuldu (özel nesne)'],
  [
    'Запрос к API v4 amoCRM (Bearer). Укажите путь и при необходимости тело JSON; для GET тело не отправляется.',
    'Request to amoCRM API v4 (Bearer). Set path and JSON body if needed; GET sends no body.',
    'amoCRM API v4 (Bearer) isteği. Gerekirse yol ve JSON gövdesi; GET için gövde yok.',
  ],
  [
    'Запрос к HubSpot CRM API (Bearer). По умолчанию хост https://api.hubapi.com; для EU укажите override.',
    'Request to HubSpot CRM API (Bearer). Default host https://api.hubapi.com; for EU set override.',
    'HubSpot CRM API (Bearer) isteği. Varsayılan https://api.hubapi.com; AB için override.',
  ],
  ['Запрос amoCRM (API v4)', 'amoCRM request (API v4)', 'amoCRM isteği (API v4)'],
  ['Запрос Google Ads API', 'Google Ads API request', 'Google Ads API isteği'],
  ['Запрос HubSpot (CRM API)', 'HubSpot request (CRM API)', 'HubSpot isteği (CRM API)'],
  ['Запрос Meta Ads (Graph)', 'Meta Ads request (Graph)', 'Meta Ads isteği (Graph)'],
  ['Значение *', 'Value *', 'Değer *'],
  ['Изменить статус', 'Change status', 'Durumu değiştir'],
  ['Или базовый URL вебхука вручную', 'Or webhook base URL manually', 'Veya webhook temel URL’sini elle'],
  ['Или URL Catch Hook вручную (hooks.zapier.com)', 'Or Catch Hook URL manually (hooks.zapier.com)', 'Veya Catch Hook URL’si elle (hooks.zapier.com)'],
  ['Или URL webhook вручную', 'Or webhook URL manually', 'Veya webhook URL’si elle'],
  ['Имя отправителя', 'From name', 'Gönderen adı'],
  ['Имя поля *', 'Field name *', 'Alan adı *'],
  ['Интеграция из маркетинга (рекомендуется)', 'Marketing integration (recommended)', 'Pazarlama entegrasyonu (önerilir)'],
  [
    'Интервал события в Graph задаётся в UTC (корректный момент времени в календаре пользователя).',
    'The event interval in Graph is set in UTC (correct instant in the user’s calendar).',
    'Graph’ta etkinlik aralığı UTC olarak ayarlanır (kullanıcı takviminde doğru an).',
  ],
  [
    'Использовать вложенное поле data (ответ Google Ads / Meta)',
    'Use nested data field (Google Ads / Meta response)',
    'İç içe data alanını kullan (Google Ads / Meta yanıtı)',
  ],
  ['Используется шаблон', 'Template in use', 'Şablon kullanılıyor'],
  [
    'Как отображается «От кого» в почте. По умолчанию Lumiva CRM.',
    'How “From” appears in email. Default: Lumiva CRM.',
    'E-postada «Kimden» nasıl görünür. Varsayılan: Lumiva CRM.',
  ],
  ['Канал доставки', 'Delivery channel', 'Teslimat kanalı'],
  ['Канал отправки', 'Send channel', 'Gönderim kanalı'],
  [
    'Карточка в Microsoft Teams через Office 365 Incoming Webhook (Connector).',
    'Card in Microsoft Teams via Office 365 Incoming Webhook (Connector).',
    'Office 365 Incoming Webhook (Connector) ile Microsoft Teams’te kart.',
  ],
  ['Компании', 'Companies', 'Şirketler'],
  ['Компания обновлена', 'Company updated', 'Şirket güncellendi'],
  ['Компания создана', 'Company created', 'Şirket oluşturuldu'],
  ['Конвертировать', 'Convert', 'Dönüştür'],
  ['Контакт обновлен', 'Contact updated', 'Kişi güncellendi'],
  ['Контакт создан', 'Contact created', 'Kişi oluşturuldu'],
  ['Контакты', 'Contacts', 'Kişiler'],
  ['Курс для {{currency}}', 'Rate for {{currency}}', '{{currency}} için kur'],
  ['Лид назначен ответственному', 'Lead assigned to owner', 'Lead sorumluya atandı'],
  ['Лид обновлен', 'Lead updated', 'Lead güncellendi'],
  ['Лид создан', 'Lead created', 'Lead oluşturuldu'],
  ['Лид: {{lead.name}}', 'Lead: {{lead.name}}', 'Lead: {{lead.name}}'],
  ['Лиды', 'Leads', 'Leadler'],
  ['Маркетинг · интеграции', 'Marketing · integrations', 'Pazarlama · entegrasyonlar'],
  ['Маркетинг (трафик и реклама)', 'Marketing (traffic and ads)', 'Pazarlama (trafik ve reklamlar)'],
  ['Метод', 'Method', 'Metot'],
  ['Метод REST', 'REST method', 'REST metodu'],
  ['Название *', 'Name *', 'Ad *'],
  ['Название события', 'Event title', 'Etkinlik başlığı'],
  [
    'Например https://company.amocrm.ru — как в подключении.',
    'For example https://company.amocrm.ru — as in the connection.',
    'Örn. https://company.amocrm.ru — bağlantıdaki gibi.',
  ],
  [
    'Например UTC или Europe/Moscow — для полей start/end в API.',
    'For example UTC or Europe/Moscow — for start/end fields in the API.',
    'Örn. UTC veya Europe/Moscow — API’de start/end alanları için.',
  ],
  [
    'Настройте правило IF/THEN для автоматизации процессов',
    'Configure an IF/THEN rule to automate processes',
    'Süreçleri otomatikleştirmek için IF/THEN kuralı yapılandırın',
  ],
  ['Не использовать шаблон (ввести вручную)', 'Do not use template (enter manually)', 'Şablon kullanma (elle gir)'],
  ['Нет аккаунтов', 'No accounts', 'Hesap yok'],
  ['Нет активной интеграции Google Ads в маркетинге.', 'No active Google Ads integration in Marketing.', 'Pazarlamada aktif Google Ads entegrasyonu yok.'],
  ['Нет активной интеграции Meta Ads в маркетинге.', 'No active Meta Ads integration in Marketing.', 'Pazarlamada aktif Meta Ads entegrasyonu yok.'],
  ['Нет подключения Битрикс24.', 'No Bitrix24 connection.', 'Bitrix24 bağlantısı yok.'],
  ['Нет подключения amoCRM.', 'No amoCRM connection.', 'amoCRM bağlantısı yok.'],
  [
    'Нет подключения Google Ads в «Автоматизации → Интеграции». Это нужно только если не используете маркетинговую интеграцию выше.',
    'No Google Ads connection under Automations → Integrations. Needed only if you do not use the marketing integration above.',
    'Otomasyonlar → Entegrasyonlar’da Google Ads bağlantısı yok. Yukarıdaki pazarlama entegrasyonunu kullanmıyorsanız gerekir.',
  ],
  ['Нет подключения Google Calendar.', 'No Google Calendar connection.', 'Google Calendar bağlantısı yok.'],
  ['Нет подключения HubSpot.', 'No HubSpot connection.', 'HubSpot bağlantısı yok.'],
  ['Нет подключения Mailchimp.', 'No Mailchimp connection.', 'Mailchimp bağlantısı yok.'],
  [
    'Нет подключения Meta Ads в «Автоматизации → Интеграции». Нужно только если не используете маркетинговую интеграцию выше.',
    'No Meta Ads connection under Automations → Integrations. Needed only if you do not use the marketing integration above.',
    'Otomasyonlar → Entegrasyonlar’da Meta Ads bağlantısı yok. Yukarıdaki pazarlama entegrasyonunu kullanmıyorsanız gerekir.',
  ],
  ['Нет подключения Outlook.', 'No Outlook connection.', 'Outlook bağlantısı yok.'],
  ['Нет подключения Teams.', 'No Teams connection.', 'Teams bağlantısı yok.'],
  ['Нет подключения WhatsApp.', 'No WhatsApp connection.', 'WhatsApp bağlantısı yok.'],
  ['Нет подключения Zapier.', 'No Zapier connection.', 'Zapier bağlantısı yok.'],
  ['Нет сохранённого подключения Slack.', 'No saved Slack connection.', 'Kayıtlı Slack bağlantısı yok.'],
  ['Нет шаблонов', 'No templates', 'Şablon yok'],
];
